# Generated by Django 5.0.6 on 2025-07-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "start_year"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("rank", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=200)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                (
                    "pdf_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 key for the memorial PDF",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casualties",
                        to="memorial.conflict",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
