# Generated by Django 5.0.6 on 2025-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="class_year",
            field=models.IntegerField(
                blank=True, help_text="VMI graduation year (e.g., 1965)", null=True
            ),
        ),
    ]
