# Generated by Django 5.0.6 on 2025-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial", "0002_person_class_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="death_description",
            field=models.TextField(
                blank=True,
                help_text="Description of how this person died (e.g., 'Killed in action during the Battle of Normandy')",
            ),
        ),
    ]
