# Generated by Django 5.0.6 on 2025-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial", "0003_person_death_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="death_date_precision",
            field=models.CharField(
                blank=True,
                choices=[("day", "Day"), ("month", "Month"), ("year", "Year")],
                default="day",
                help_text="Precision of the death date (year only, month and year, or full date)",
                max_length=10,
            ),
        ),
    ]
