# Generated by Django 5.0.6 on 2025-07-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial", "0004_person_death_date_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contributor_email",
                    models.EmailField(
                        help_text="Email of the person submitting this contribution",
                        max_length=254,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("both", "Both"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, help_text="Text content of the contribution"
                    ),
                ),
                (
                    "content_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image contribution",
                        null=True,
                        upload_to="contributions/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="memorial.person",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "status"],
                        name="memorial_co_person__8f13d8_idx",
                    ),
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="memorial_co_status_0bff92_idx",
                    ),
                ],
            },
        ),
    ]
