# Generated by Django 5.0.6 on 2025-10-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial", "0005_contribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="class_letter",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional letter suffix for class year (e.g., 'M' for 1956M)",
                max_length=1,
            ),
        ),
    ]
