# Generated by Django 5.0.6 on 2025-11-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial", "0006_person_class_letter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the award (e.g., 'Medal of Honor (Army)')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief description for display on cards (1-2 sentences)"
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        help_text="Detailed description for the award detail page"
                    ),
                ),
                (
                    "image_filename",
                    models.CharField(
                        blank=True,
                        help_text="Image slug (e.g., 'MoHArmy' maps to '/MoHArmy.jpg' on frontend)",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PersonAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of times this award was received"
                    ),
                ),
                (
                    "date_awarded",
                    models.DateField(
                        blank=True,
                        help_text="Date the award was received (if known)",
                        null=True,
                    ),
                ),
                (
                    "citation",
                    models.TextField(
                        blank=True,
                        help_text="Citation or specific details for this award",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_awards",
                        to="memorial.award",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_awards",
                        to="memorial.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Award",
                "verbose_name_plural": "Person Awards",
                "ordering": ["award__order", "award__name"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="awards",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipients",
                through="memorial.PersonAward",
                to="memorial.award",
            ),
        ),
        migrations.AddIndex(
            model_name="personaward",
            index=models.Index(
                fields=["person", "award"], name="memorial_pe_person__aaea16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personaward",
            index=models.Index(fields=["award"], name="memorial_pe_award_i_0ee16c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="personaward",
            unique_together={("person", "award")},
        ),
    ]
